---

- hosts: all
  become: true 
  tasks:

  - name: Install apache2 package
    apt:
      name: apache2
    when: ansible_distribution == "Kali"

  - name: Start apache2 service 
    service:
      name: apache2
      state: started 
    when: ansible_distribution == "Kali"

  - name: Add php support for apache2 
    apt:
      name: libapache2-mod-php
      state: latest
    when: ansible_distribution == "Kali"

  

    