---

- hosts: all
  become: true 
  tasks:

  - name: Install apache and PHP package
    package:
      name:
        - "{{apache_package}}"
        - "{{php_package}}"
      state: latest
      #update_cache: true
  
  - name: copy default html file
    tags: apache,apache2
    copy:
     src: default_site.html
     dest: /var/www/html/index.html 
     owner: root 
     group: root 
     mode: 0644

  - name: Start apache2 service 
    service:
      name: "{{apache_package}}"
      state: started 
    when: ansible_distribution == "Kali"



  

    