---

- hosts: all
  become: true 
  tasks:

  - name: Install apache and PHP package
    package:
      name:
        - "{{apache_package}}"
        - "{{php_package}}"
      state: latest
      #update_cache: true
  
  - name: copy default html file
    tags: apache,apache2
    copy:
     src: default_site.html
     dest: /var/www/html/index.html 
     owner: root 
     group: root 
     mode: 0644
  
  - name: install unzip package
    package: 
      name: unzip

  - name: install terraform 
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.6.3/terraform_1.6.3_linux_arm64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root

  - name: Start apache2 service 
    service:
      name: "{{apache_package}}"
      state: started 
    when: ansible_distribution == "Kali"



  

    